# Generated by Django 5.1.1 on 2024-10-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('superApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('age', models.IntegerField()),
                ('roll_no', models.IntegerField(unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Superheroes',
        ),
    ]
